### ISSUE TITLE
windows版本不能用

### ISSUE THREAD

**Issue by kay-zhu** [OwO-Network/nexttrace-experiment#34]
## 你正在使用哪个版本的 nexttrace？

[nexttrace_windows_amd64.exe](https://github.com/OwO-Network/nexttrace-experiment/releases/download/v0.3.2-beta.1/nexttrace_windows_amd64.exe)

## 你看到的异常现象是什么？
无法开启

一闪即过

**Comment by sjlleo** [comment]
NextTrace 是命令行操作，所以不能直接打开，你需要使用 Windows CMD 或者终端使用

如果需要全界面操作，推荐使用 [OpenTrace](https://github.com/Archeb/opentrace)，你只需要把新版的核心放在里面就可以跑了

谢谢

**Comment by kay-zhu** [comment]
请问核心是放哪个文件？谢谢

发自我的 iPhone

在 2023年8月20日，13:40，sjlleo ***@***.***> 写道：

﻿

Closed #34<https://github.com/OwO-Network/nexttrace-experiment/issues/34> as completed.

**Comment by kay-zhu** [comment]
OpenTrace和NextTrace ，前面的全部是*号，咋办？
