### ISSUE TITLE
OpenTrace和NextTrace ，前面的全部是*号

### ISSUE THREAD

**Issue by kay-zhu** [OwO-Network/nexttrace-experiment#35]
## 你正在使用哪个版本的 nexttrace？

v1.1.7-2

AMD64

## 你看到的异常现象是什么？

除了最后一个，其余全是*号

## 请附上你的命令

NextTrace v1.1.7-2 2023-06-06T19:36:21Z b1edef3
IP Geo Data Provider: LeoMoeAPI
traceroute to 158.180.36.249, 30 hops max, 52 bytes packets
1   *
2   *
3   *
4   *
5   *
6   *
7   *
8   *
9   *
10  *
11  *
12  158.xx.xx.xxx  AS31898                   德国 黑森州 美因河畔法兰克福  cloud.oracle.com
                                              201.86 ms / 209.73 ms / 202.04 ms

**Comment by sjlleo** [comment]
这个问题已经有人提过了，Google/Bing搜索一下就能找到了
